#!/usr/bin/env bash

# SIGTERM siqnalı alanda "I am invincible!!!" mesajını göstərən funksiya
invincible() {
    echo "I am invincible!!!"
}

# SIGTERM siqnalını tutmaq üçün trap əmri
trap invincible SIGTERM

# Sonsuz dövrə
while true
do
    echo "To infinity and beyond"
    sleep 2
done
